version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME:$CIRCLE_SHA1


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
#   ci-cd-workflow:
#     jobs:
#       - build_and_deploy_docker_image
