name: SLAM Team2 CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Download KITTI Dataset
      run: |
        mkdir -p kitti/dataset/
        cd kitti/dataset/
        curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=1kXFiGgqikvdyeQK9bK36UkepRjchfAwi" > /dev/null
        curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=1kXFiGgqikvdyeQK9bK36UkepRjchfAwi" -o KITTI_data.zip
        unzip KITTI_data.zip
        rm KITTI_data.zip
        
    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Build and Push Docker Image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: sws1719/slam_team2:latest
        platforms: linux/amd64
        
    - name: Test and Generate Report
      run: |
        docker run --rm -i \
          -v $(pwd):/app \
          -v $(pwd)/kitti:/kitti \
          sws1719/slam_team2:latest \
          cd slam_team2 \
          python run_and_generate_report.py --dataset_path /kitti --output-dir ./report
        
    - name: Push Report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./report
