name: SLAM Team2 CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Download KITTI Dataset
      run: |
        mkdir -p data/
        cd data/
        curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=1PEd-Z0OXFSOlzDUSh-nH2PqTC6NVWG4Q" > /dev/null
        curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=1PEd-Z0OXFSOlzDUSh-nH2PqTC6NVWG4Q" -o superpoint.pt
        curl -c ./cookie -s -L "https://drive.google.com/uc?export=download&id=1kXFiGgqikvdyeQK9bK36UkepRjchfAwi" > /dev/null
        curl -Lb ./cookie "https://drive.google.com/uc?export=download&confirm=`awk '/download/ {print $NF}' ./cookie`&id=1kXFiGgqikvdyeQK9bK36UkepRjchfAwi" -o KITTI_data.zip
        unzip KITTI_data.zip
        rm KITTI_data.zip
        
    - name: docker pull
      run: |
        docker pull sws1719/slam_team2:latest
        
    - name: Test and Generate Report
      run: |
        docker run --rm -i \
          -v $(pwd)/data:/root/Documents/RTAB-Map \
          sws1719/slam_team2:latest \
          sh -c "mkdir /root/Documents/RTAB-Map/report && ldconfig && source /ros_entrypoint.sh && cd slam_team2 && git pull && chmod 777 run_and_generate_report.py && ./run_and_generate_report.py --dataset_path /root/Documents/RTAB-Map/ --output_dir /root/Documents/RTAB-Map/report/"
          
        
    - name: Push Report to Github Pages
      run: |
        git config --local user.email "sws1719@naver.com"
        git config --local user.name "songwon31"
        git add data/report/
        git commit -m "Generate report"
        git push https://${{ secrets.ACCESS_TOKEN }}@github.com/songwon31/slam_team2.git HEAD:main
