name: SLAM Team2 CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: docker pull
      run: |
        docker pull sws1719/slam_team2:latest
        
    - name: Test and Generate Report
      run: |
        docker run --rm -i \
          -v $(pwd)/data:/root/Documents/RTAB-Map \
          sws1719/slam_team2:latest \
          sh -c "mkdir /root/Documents/RTAB-Map/report && touch /root/Documents/RTAB-Map/report/test.txt"
          
        
    - name: Push Report to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: $(pwd)/data/report
