name: git push test

on:
  push:
    branches:
      - main

jobs:
  git_pull_and_push_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: docker pull
      run: |
        docker pull sws1719/slam_team2:latest
        
    - name: Test and Generate Report
      run: |
        docker run --rm -i \
          -v $(pwd)/data:/root/Documents/RTAB-Map \
          sws1719/slam_team2:latest \
          sh -c "mkdir /root/Documents/RTAB-Map/report && touch /root/Documents/RTAB-Map/report/test.txt"
          
    - name: Push Report to Github Pages
      run: |
        git config --local user.email "sws1719@naver.com"
        git config --local user.name "songwon31"
        git add data/
        git commit -m "Generate report"
        git push https://${{ secrets.ACCESS_TOKEN }}@github.com/songwon31/slam_team2.git HEAD:main
        
